[package]
name = "pa-tcp"
version = "0.1.0"
authors = ["aragaer <aragaer@gmail.com>"]

[dependencies]
bytes = "0.4.11"
encoding = "0.2"
getopts = "0.2.18"
mio = "0.6.4"
serde = "1.0"
serde_json = "1.0"
slab = "0.4.2"